apiVersion: v1
kind: Namespace
metadata:
  name: spark
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dataflow-spark
  namespace: spark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dataflow-spark-runner
  namespace: spark
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dataflow-spark-runner
  namespace: spark
subjects:
  - kind: ServiceAccount
    name: dataflow-spark
    namespace: spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dataflow-spark-runner
